[build]
  publish = "public"
  command = "gatsby build"

[build.environment]
  NODE_VERSION = "18.12.1"
  NPM_VERSION = "8.4.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/**/*.html"
  [headers.values]
    Cache-Control = '''
      public,
      max-age=0,
      must-revalidate'''

[[headers]]
  for = "/page-data/*.json"
  [headers.values]
    Cache-Control = '''
      public,
      max-age=0,
      must-revalidate'''

[[headers]]
  for = "/app-data.json"
  [headers.values]
    Cache-Control = '''
      public,
      max-age=0,
      must-revalidate'''

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = '''
      public,
      max-age=31536000,
      immutable'''

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = '''
      public,
      max-age=365000000,
      immutable'''

[[redirects]]
  from = "https://kaisboulakhlas.netlify.app/*"
  to = "https://kaisboulakhlas.com/:splat"
  status = 301
  force = true

# Asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true