backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: "static/img"
public_folder: "../../static/img"

collections:
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "titre", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "serviceImage", name: "serviceimage", widget: "image" }

  - name: "projets"
    label: "Projets"
    folder: "content/projets"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Project Link", name: "projectlink", widget: "string" }
      - { label: "Code link", name: "codelink", widget: "string" }
      - { label: "Project Image", name: "projectimage", widget: "image" }
      - { label: "Type", name: "type", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
