backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: "static/img"
public_folder: "../../static/img"

collections:
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{titre}}"
    fields:
      - { label: "Titre", name: "titre", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Service image", name: "serviceimage", widget: "image" }
      - { label: "Type of file", name: "typeoffile", widget: "string" }

  - name: "projets"
    label: "Projets"
    folder: "content/projets"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Project Link", name: "projectlink", widget: "string" }
      - { label: "Code link", name: "codelink", widget: "string" }
      - { label: "Project Image", name: "projectimage", widget: "image" }
      - { label: "Type of file", name: "typeoffile", widget: "string" }
      - { label: "Type", name: "type", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "competences"
    label: "Compétences"
    folder: "content/competences"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Bg Color", name: "bgcolor", widget: "string" }
      - { label: "Icon", name: "icon", widget: "image" }
      - { label: "Type of file", name: "typeoffile", widget: "string" }

  - name: "experience"
    label: "Experience"
    folder: "content/experiences"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "ID", name: "id", widget: "number", value_type: "int", min: 1, max: 101, step: 1  }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tag", name: "tag", widget: "string" }
      - { label: 'Start Date', name: 'startdate', widget: 'string'}
      - { label: 'End Date', name: 'enddate', widget: 'string'}
      - { label: "Color", name: "color", widget: "string" }
      - { label: "Type of file", name: "typeoffile", widget: "string" }

  - name: "curriculumvitae"
    label: "CV"
    folder: "content/cv"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Type of file", name: "typeoffile", widget: "string" }
